import {
  User,
  CreatorProfile,
  SocialAccount,
  Content,
  Publication,
  PublishingAttempt,
  Task,
  NotificationItem,
  ProductionPlan,
  ShootingChecklistItem,
  BasicAnalyticsMetric,
} from '@/types';

export const SEED_USER: User = {
  id: 'usr_01jd72948',
  email: 'eric@creatorcc.com',
  name: 'Eric Dollar',
  avatarUrl: '',
  timezone: 'Africa/Lagos',
  status: 'ACTIVE',
  createdAt: '2026-08-01T08:00:00Z',
};

export const SEED_PROFILE: CreatorProfile = {
  userId: 'usr_01jd72948',
  displayName: 'Eric Dollar',
  bio: 'Software engineer & tech creator sharing deep dives into TypeScript, web development, and minimal workspace aesthetics.',
  creatorType: 'YouTuber',
  primaryPlatforms: ['youtube', 'instagram', 'tiktok'],
  publicUrl: 'https://youtube.com/@creator_daily',
  onboardingCompleted: true,
};

export const SEED_ACCOUNTS: SocialAccount[] = [
  {
    id: 'acc_yt_01',
    userId: 'usr_01jd72948',
    platform: 'youtube',
    accountName: 'Code Creator Studio',
    accountHandle: '@code_creator',
    status: 'CONNECTED',
    lastSyncedAt: '2026-09-24T06:30:00Z',
    connectedAt: '2026-06-14T10:00:00Z',
  },
  {
    id: 'acc_ig_02',
    userId: 'usr_01jd72948',
    platform: 'instagram',
    accountName: 'Eric Creates Daily',
    accountHandle: '@creator_daily',
    status: 'NEEDS_REAUTHORIZATION',
    errorMessage: 'OAuth credential token expired or revoked by Instagram. Reauthorization required.',
    lastSyncedAt: '2026-09-23T14:00:00Z',
    connectedAt: '2026-01-10T09:30:00Z',
  },
  {
    id: 'acc_tt_03',
    userId: 'usr_01jd72948',
    platform: 'tiktok',
    accountName: 'Tech Shorts',
    accountHandle: '@creator_shorts',
    status: 'DISCONNECTED',
    lastSyncedAt: '2026-09-10T12:00:00Z',
    connectedAt: '2026-04-05T11:00:00Z',
  },
  {
    id: 'acc_li_04',
    userId: 'usr_01jd72948',
    platform: 'linkedin',
    accountName: 'Eric Dollar',
    accountHandle: 'in/eric-dollar',
    status: 'CONNECTED',
    lastSyncedAt: '2026-09-24T05:00:00Z',
    connectedAt: '2026-05-18T16:20:00Z',
  },
  {
    id: 'acc_fb_05',
    userId: 'usr_01jd72948',
    platform: 'facebook',
    accountName: 'Creator Command Page',
    accountHandle: 'fb.com/creatorcc',
    status: 'DISCONNECTED',
    lastSyncedAt: '2026-08-15T09:00:00Z',
    connectedAt: '2026-03-01T12:00:00Z',
  },
];

export const SEED_CONTENT: Content[] = [
  {
    id: 'cnt_ts_mistakes',
    userId: 'usr_01jd72948',
    title: '5 TypeScript Mistakes',
    description: 'Avoid these common runtime pitfalls and type system bypasses that lead to weak typings in production codebases.',
    caption: 'Here are 5 common mistakes React developers make when writing TypeScript. Fix your typings today!',
    notes: 'Cover any casting, unhandled null checks, excessive type assertions, and missing discriminated unions.',
    contentType: 'video',
    status: 'READY',
    targetPlatforms: ['youtube', 'instagram', 'tiktok'],
    deadline: '2026-09-28T18:00:00Z',
    tags: ['typescript', 'react', 'coding', 'webdev'],
    createdAt: '2026-08-28T10:00:00Z',
    updatedAt: '2026-08-30T14:30:00Z',
    versions: [
      {
        id: 'ver_ts_yt',
        contentId: 'cnt_ts_mistakes',
        platform: 'youtube',
        platformAccountId: 'acc_yt_01',
        title: '5 Common TypeScript Mistakes Every React Developer Makes (And How to Fix Them)',
        description: 'In this video, we cover the 5 most common type safety pitfalls React developers encounter when using TypeScript. From incorrect event handling typing to abusing the any type, learn how to keep your codebase secure and robust.',
        hashtags: ['typescript', 'react', 'programming', 'developer', 'mistakes'],
        category: 'Science & Technology',
        visibility: 'Public',
        status: 'Published',
        updatedAt: '2026-08-30T14:30:00Z',
      },
      {
        id: 'ver_ts_ig',
        contentId: 'cnt_ts_mistakes',
        platform: 'instagram',
        platformAccountId: 'acc_ig_02',
        caption: '5 Common TypeScript Mistakes Every React Developer Makes (And How to Fix Them)\n\nStop using "any" and fix your generic parameters! Full breakdown in description.',
        hashtags: ['typescript', 'coding', 'reactjs', 'webdev'],
        callToAction: 'https://creator.example/ts-mistakes',
        postType: 'Reel',
        status: 'Failed',
        updatedAt: '2026-08-30T14:30:00Z',
      },
      {
        id: 'ver_ts_tt',
        contentId: 'cnt_ts_mistakes',
        platform: 'tiktok',
        platformAccountId: 'acc_tt_03',
        caption: 'Wait for #4... 5 common TypeScript mistakes you are probably making #coding #tech #tutorial',
        hashtags: ['coding', 'tech', 'tutorial', 'fyp'],
        soundName: 'Original Sound - Code Creator',
        status: 'Published',
        updatedAt: '2026-08-30T14:32:00Z',
      },
    ],
  },
  {
    id: 'cnt_autumn_workspace',
    userId: 'usr_01jd72948',
    title: 'Autumn Workspace Setup',
    description: 'Bringing warm autumn tones, cozy workspace lighting, and new tech setup layout suggestions. This video will explore desk layout redesign, plant placements, and soft lighting configurations to enhance productivity as the seasons change.',
    caption: 'Transforming my workspace for cozy autumn productivity! Full video on YouTube and aesthetic tour on IG.',
    notes: 'Record B-roll with 3200K warm key light. Focus on ergonomic desk riser and mechanical keyboard sound test.',
    contentType: 'video',
    status: 'DRAFT',
    targetPlatforms: ['youtube', 'instagram', 'tiktok'],
    deadline: '2026-09-30T17:00:00Z',
    tags: ['setup', 'workspace', 'autumn', 'desktour', 'productivity'],
    createdAt: '2026-09-12T14:15:00Z',
    updatedAt: '2026-09-12T14:15:00Z',
    versions: [
      {
        id: 'ver_autumn_yt',
        contentId: 'cnt_autumn_workspace',
        platform: 'youtube',
        platformAccountId: 'acc_yt_01',
        title: 'Autumn Workspace Setup | Minimalist & Productive (4K)',
        description: 'A deep dive into my cozy and highly optimized workspace configuration for Autumn 2026. Featuring warm desk lighting, ergonomic wood monitor risers, and the ultimate cable organization setup.',
        hashtags: ['desktour', 'minimalist', 'workspace', 'autumnvibes', 'tech'],
        category: 'Science & Technology',
        visibility: 'Public',
        status: 'Ready',
        formatNote: 'Video Essay (16:9)',
        updatedAt: '2026-09-12T14:15:00Z',
      },
      {
        id: 'ver_autumn_ig',
        contentId: 'cnt_autumn_workspace',
        platform: 'instagram',
        platformAccountId: 'acc_ig_02',
        caption: 'Bringing warm autumn vibes to the desk. Warm lights + wooden risers = ultimate focus mood 🍂',
        hashtags: ['aesthetic', 'desksetup', 'autumnvibes', 'minimalist'],
        callToAction: 'Link in Bio for gear links',
        postType: 'Reel',
        status: 'Draft',
        formatNote: 'Aesthetic Reel (9:16)',
        updatedAt: '2026-09-12T14:15:00Z',
      },
      {
        id: 'ver_autumn_tt',
        contentId: 'cnt_autumn_workspace',
        platform: 'tiktok',
        platformAccountId: 'acc_tt_03',
        caption: 'Desk setup sound check & autumn glow 🍁 #desksetup #asmr #satisfying',
        hashtags: ['desksetup', 'asmr', 'autumn'],
        soundName: 'Original ASMR Sound',
        status: 'Draft',
        formatNote: 'Setup ASMR sound check (9:16)',
        updatedAt: '2026-09-12T14:15:00Z',
      },
    ],
  },
  {
    id: 'cnt_react_hooks',
    userId: 'usr_01jd72948',
    title: 'React Hooks Tutorial',
    description: 'Comprehensive breakdown of advanced useEffect, useMemo, and custom hooks patterns in modern React 19 apps.',
    caption: 'Mastering modern React Hooks without memory leaks or unnecessary re-renders.',
    contentType: 'video',
    status: 'SCHEDULED',
    targetPlatforms: ['youtube', 'instagram'],
    deadline: '2026-09-25T10:00:00Z',
    tags: ['react', 'javascript', 'frontend', 'hooks'],
    createdAt: '2026-09-08T09:00:00Z',
    updatedAt: '2026-09-10T11:00:00Z',
    versions: [
      {
        id: 'ver_react_yt',
        contentId: 'cnt_react_hooks',
        platform: 'youtube',
        platformAccountId: 'acc_yt_01',
        title: 'Master React Hooks in 2026: Complete Practical Guide',
        description: 'Everything you need to know about React Hooks in 2026.',
        hashtags: ['react', 'webdev', 'frontend'],
        status: 'Scheduled',
        updatedAt: '2026-09-10T11:00:00Z',
      },
      {
        id: 'ver_react_ig',
        contentId: 'cnt_react_hooks',
        platform: 'instagram',
        platformAccountId: 'acc_ig_02',
        caption: '3 React hook rules every developer forgets! Check slide 2.',
        hashtags: ['reactjs', 'programming'],
        postType: 'Carousel',
        status: 'Draft',
        updatedAt: '2026-09-10T11:00:00Z',
      },
    ],
  },
  {
    id: 'cnt_css_grid',
    userId: 'usr_01jd72948',
    title: 'CSS Grid Guide',
    description: 'Visual comparison of CSS Grid vs Flexbox with 10 real-world responsive layout challenges.',
    caption: 'Stop struggling with CSS layouts. Here is when to use Grid vs Flexbox.',
    contentType: 'short_video',
    status: 'DRAFT',
    targetPlatforms: ['instagram', 'tiktok'],
    deadline: '2026-09-26T15:00:00Z',
    tags: ['css', 'frontend', 'design', 'grid'],
    createdAt: '2026-09-22T08:30:00Z',
    updatedAt: '2026-09-22T08:30:00Z',
    versions: [
      {
        id: 'ver_css_ig',
        contentId: 'cnt_css_grid',
        platform: 'instagram',
        platformAccountId: 'acc_ig_02',
        caption: 'Grid or Flexbox? Save this for your next frontend build!',
        hashtags: ['css3', 'webdesign', 'codetips'],
        postType: 'Feed Post',
        status: 'Draft',
        updatedAt: '2026-09-22T08:30:00Z',
      },
    ],
  },
  {
    id: 'cnt_modern_desk',
    userId: 'usr_01jd72948',
    title: 'Modern Desk Setup & Aesthetics Tour',
    description: 'Clean Scandinavian desk setup showcase with wireless cable management and dual monitor ergonomic arms.',
    caption: 'Full modern setup tour is now live!',
    contentType: 'video',
    status: 'PUBLISHED',
    targetPlatforms: ['youtube', 'instagram', 'linkedin'],
    deadline: '2026-09-10T11:30:00Z',
    tags: ['desk', 'productivity', 'minimalism'],
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-10T11:30:00Z',
    versions: [
      {
        id: 'ver_modern_yt',
        contentId: 'cnt_modern_desk',
        platform: 'youtube',
        platformAccountId: 'acc_yt_01',
        title: 'The Ultimate Minimalist Desk Tour 2026',
        status: 'Published',
        updatedAt: '2026-09-10T11:30:00Z',
      },
    ],
  },
  {
    id: 'cnt_saas_alone',
    userId: 'usr_01jd72948',
    title: 'How I Built My SaaS Alone in 2026',
    description: 'Architecture and tech stack breakdown of bootstrapping a full software product as a solo engineer.',
    caption: 'The brutal truth about building a micro-SaaS alone.',
    contentType: 'video',
    status: 'DRAFT',
    targetPlatforms: ['youtube', 'linkedin'],
    deadline: '2026-10-05T12:00:00Z',
    tags: ['saas', 'indiehackers', 'coding', 'business'],
    createdAt: '2026-09-05T17:45:00Z',
    updatedAt: '2026-09-05T17:45:00Z',
  },
  {
    id: 'cnt_flexbox_tut',
    userId: 'usr_01jd72948',
    title: 'Flexbox Tutorial',
    description: 'Master align-items, justify-content, and flex-grow with visual diagrams.',
    caption: 'Visual cheat-sheet for CSS Flexbox alignment.',
    contentType: 'video',
    status: 'READY',
    targetPlatforms: ['youtube', 'linkedin'],
    deadline: '2026-10-01T14:00:00Z',
    tags: ['css', 'flexbox', 'webdev'],
    createdAt: '2026-09-14T11:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'cnt_node_best_practices',
    userId: 'usr_01jd72948',
    title: 'Node.js Best Practices',
    description: '10 defensive programming habits for production Node.js and TypeScript microservices.',
    caption: 'Production tips for backend Node developers.',
    contentType: 'text',
    status: 'IDEA',
    targetPlatforms: ['linkedin'],
    tags: ['nodejs', 'backend', 'typescript'],
    createdAt: '2026-09-18T16:00:00Z',
    updatedAt: '2026-09-18T16:00:00Z',
  },
  {
    id: 'cnt_js_tips',
    userId: 'usr_01jd72948',
    title: 'JavaScript Tips',
    description: 'Quick functional programming utilities using Array.prototype.reduce and flatMap.',
    caption: 'Clean code snippets for daily JS work.',
    contentType: 'image',
    status: 'IDEA',
    targetPlatforms: ['instagram', 'linkedin'],
    tags: ['javascript', 'tips'],
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
];

export const SEED_PUBLICATIONS: Publication[] = [
  {
    id: 'pub_ts_yt',
    userId: 'usr_01jd72948',
    contentId: 'cnt_ts_mistakes',
    contentTitle: '5 TypeScript Mistakes',
    contentVersionId: 'ver_ts_yt',
    platform: 'youtube',
    platformAccountId: 'acc_yt_01',
    accountName: 'Code Creator Studio',
    accountHandle: '@code_creator',
    status: 'PUBLISHED',
    scheduledAt: '2026-08-30T14:30:00Z',
    displayTimezone: 'Africa/Lagos',
    publishedAt: '2026-08-30T14:30:00Z',
    attemptsCount: 2,
    createdAt: '2026-08-29T12:00:00Z',
    updatedAt: '2026-08-30T14:30:00Z',
  },
  {
    id: 'pub_ts_ig',
    userId: 'usr_01jd72948',
    contentId: 'cnt_ts_mistakes',
    contentTitle: '5 TypeScript Mistakes',
    contentVersionId: 'ver_ts_ig',
    platform: 'instagram',
    platformAccountId: 'acc_ig_02',
    accountName: 'Eric Creates Daily',
    accountHandle: '@creator_daily',
    status: 'FAILED',
    scheduledAt: '2026-08-30T14:30:00Z',
    displayTimezone: 'Africa/Lagos',
    lastErrorReason: 'Rate limit exceeded: too many publishing attempts in the last hour. Platform API limit (429).',
    attemptsCount: 2,
    createdAt: '2026-08-29T12:00:00Z',
    updatedAt: '2026-08-30T14:30:00Z',
  },
  {
    id: 'pub_ts_tt',
    userId: 'usr_01jd72948',
    contentId: 'cnt_ts_mistakes',
    contentTitle: '5 TypeScript Mistakes',
    contentVersionId: 'ver_ts_tt',
    platform: 'tiktok',
    platformAccountId: 'acc_tt_03',
    accountName: 'Tech Shorts',
    accountHandle: '@creator_shorts',
    status: 'PUBLISHED',
    scheduledAt: '2026-08-30T14:32:00Z',
    displayTimezone: 'Africa/Lagos',
    publishedAt: '2026-08-30T14:32:00Z',
    attemptsCount: 1,
    createdAt: '2026-08-29T12:00:00Z',
    updatedAt: '2026-08-30T14:32:00Z',
  },
  {
    id: 'pub_react_yt',
    userId: 'usr_01jd72948',
    contentId: 'cnt_react_hooks',
    contentTitle: 'React Hooks Tutorial',
    contentVersionId: 'ver_react_yt',
    platform: 'youtube',
    platformAccountId: 'acc_yt_01',
    accountName: 'Code Creator Studio',
    accountHandle: '@code_creator',
    status: 'SCHEDULED',
    scheduledAt: '2026-09-25T10:00:00Z',
    displayTimezone: 'Africa/Lagos',
    attemptsCount: 0,
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
];

export const SEED_ATTEMPTS: PublishingAttempt[] = [
  {
    id: 'att_ts_yt_01',
    publicationId: 'pub_ts_yt',
    contentVersionId: 'ver_ts_yt',
    platform: 'youtube',
    platformAccountId: 'acc_yt_01',
    status: 'FAILED',
    attemptNumber: 1,
    startedAt: '2026-08-30T14:00:00Z',
    finishedAt: '2026-08-30T14:02:00Z',
    errorReason: 'Upload stream connection timeout during chunk transmission.',
    errorCode: 'UPLOAD_TIMEOUT',
    isRetry: false,
  },
  {
    id: 'att_ts_yt_02',
    publicationId: 'pub_ts_yt',
    contentVersionId: 'ver_ts_yt',
    platform: 'youtube',
    platformAccountId: 'acc_yt_01',
    status: 'SUCCESS',
    attemptNumber: 2,
    startedAt: '2026-08-30T14:28:00Z',
    finishedAt: '2026-08-30T14:30:00Z',
    externalUrl: 'https://youtube.com/watch?v=mock_typescript5',
    externalId: 'mock_typescript5',
    isRetry: true,
  },
  {
    id: 'att_ts_ig_01',
    publicationId: 'pub_ts_ig',
    contentVersionId: 'ver_ts_ig',
    platform: 'instagram',
    platformAccountId: 'acc_ig_02',
    status: 'FAILED',
    attemptNumber: 1,
    startedAt: '2026-08-30T14:00:00Z',
    finishedAt: '2026-08-30T14:01:00Z',
    errorReason: 'Rate limit exceeded: too many publishing attempts in the last hour.',
    errorCode: 'API_LIMIT_EXCEEDED',
    isRetry: false,
  },
  {
    id: 'att_ts_ig_02',
    publicationId: 'pub_ts_ig',
    contentVersionId: 'ver_ts_ig',
    platform: 'instagram',
    platformAccountId: 'acc_ig_02',
    status: 'FAILED',
    attemptNumber: 2,
    startedAt: '2026-08-30T14:29:00Z',
    finishedAt: '2026-08-30T14:30:00Z',
    errorReason: 'Rate limit exceeded: too many publishing attempts in the last hour.',
    errorCode: 'API_LIMIT_EXCEEDED',
    isRetry: true,
  },
  {
    id: 'att_ts_tt_01',
    publicationId: 'pub_ts_tt',
    contentVersionId: 'ver_ts_tt',
    platform: 'tiktok',
    platformAccountId: 'acc_tt_03',
    status: 'SUCCESS',
    attemptNumber: 1,
    startedAt: '2026-08-30T14:30:00Z',
    finishedAt: '2026-08-30T14:32:00Z',
    externalUrl: 'https://tiktok.com/@mock/video/9923',
    externalId: '9923',
    isRetry: false,
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: 'tsk_01',
    userId: 'usr_01jd72948',
    title: 'Review TikTok caption',
    description: 'Ensure hook question and hashtag group align with discovery recommendations.',
    status: 'OPEN',
    priority: 'HIGH',
    dueAt: '2026-09-24T14:00:00Z',
    contentId: 'cnt_ts_mistakes',
    contentTitle: '5 TypeScript Mistakes',
    createdAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'tsk_02',
    userId: 'usr_01jd72948',
    title: 'Upload thumbnail for YouTube',
    description: 'High-contrast 16:9 thumbnail with code snippet comparison diagram.',
    status: 'OPEN',
    priority: 'HIGH',
    dueAt: '2026-09-24T17:00:00Z',
    contentId: 'cnt_react_hooks',
    contentTitle: 'React Hooks Tutorial',
    createdAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'tsk_03',
    userId: 'usr_01jd72948',
    title: 'Schedule Instagram post',
    description: 'Verify 3-slide carousel formatting and CTA link before queueing.',
    status: 'OPEN',
    priority: 'MEDIUM',
    dueAt: '2026-09-24T18:00:00Z',
    contentId: 'cnt_css_grid',
    contentTitle: 'CSS Grid Guide',
    createdAt: '2026-09-23T11:00:00Z',
  },
  {
    id: 'tsk_04',
    userId: 'usr_01jd72948',
    title: 'Write captions for React video',
    description: 'Was due yesterday. Write 200-word SEO summary and timestamp chapters.',
    status: 'OPEN',
    priority: 'HIGH',
    dueAt: '2026-09-23T12:00:00Z',
    contentId: 'cnt_react_hooks',
    contentTitle: 'React Hooks Tutorial',
    createdAt: '2026-09-20T14:00:00Z',
  },
  {
    id: 'tsk_05',
    userId: 'usr_01jd72948',
    title: 'Outline next YouTube module on Figma constraints',
    description: 'Draft the 5 essential rules of responsive layout math in UI design.',
    status: 'OPEN',
    priority: 'MEDIUM',
    dueAt: '2026-09-26T16:00:00Z',
    createdAt: '2026-09-23T09:00:00Z',
  },
  {
    id: 'tsk_06',
    userId: 'usr_01jd72948',
    title: 'Clean desk setup for preview video',
    description: 'Dust monitors, hide monitor power lines, wipe wooden desk mat.',
    status: 'COMPLETED',
    priority: 'LOW',
    dueAt: '2026-09-22T11:00:00Z',
    completedAt: '2026-09-22T10:45:00Z',
    contentId: 'cnt_autumn_workspace',
    contentTitle: 'Autumn Workspace Setup',
    createdAt: '2026-09-20T11:00:00Z',
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    userId: 'usr_01jd72948',
    type: 'PUBLISHING_FAILED',
    title: 'Instagram publishing failed',
    message: 'Instagram publishing failed for "5 TypeScript Mistakes": Rate limit exceeded.',
    read: false,
    createdAt: '2026-09-24T07:15:00Z',
    linkTo: '/content/cnt_ts_mistakes',
    actionLabel: 'Retry',
    platform: 'instagram',
  },
  {
    id: 'notif_02',
    userId: 'usr_01jd72948',
    type: 'PLATFORM_REAUTH_REQUIRED',
    title: 'Reauthorization required',
    message: 'Instagram connection has expired or was revoked. Reconnect to resume scheduled publishing.',
    read: false,
    createdAt: '2026-09-24T06:00:00Z',
    linkTo: '/platforms',
    actionLabel: 'Reauthorize',
    platform: 'instagram',
  },
  {
    id: 'notif_03',
    userId: 'usr_01jd72948',
    type: 'TASK_OVERDUE',
    title: 'Task overdue',
    message: 'Task "Write captions for React video" is overdue (due yesterday).',
    read: false,
    createdAt: '2026-09-23T18:00:00Z',
    linkTo: '/tasks',
    actionLabel: 'View Task',
  },
  {
    id: 'notif_04',
    userId: 'usr_01jd72948',
    type: 'PUBLISHING_SUCCESS',
    title: 'Publishing complete',
    message: 'Successfully published "5 TypeScript Mistakes" to YouTube and TikTok.',
    read: true,
    createdAt: '2026-08-30T14:32:00Z',
    linkTo: '/publishing',
    actionLabel: 'View Results',
    platform: 'youtube',
  },
];

export const SEED_PRODUCTION_PLAN: ProductionPlan = {
  id: 'prod_autumn_01',
  contentId: 'cnt_autumn_workspace',
  shootLocation: 'Downtown Loft Studio - Room 4B',
  gearEquipment: ['Sony A7S III (4K 60fps)', 'Sony 24-70mm f/2.8 GM', 'Aputure 300d II Key Light (3200K)', 'Rode Wireless GO II mics'],
  participants: ['Eric Dollar (Host / Creator)', 'Sarah Chen (Lighting Tech)'],
  shootDate: '2026-09-28',
  callTime: '09:30 AM',
  readinessNotes: 'Ensure warm ambient tone (3200K). Shoot 9:16 vertical b-roll alongside main 16:9 master stream.',
  updatedAt: '2026-09-23T16:00:00Z',
};

export const SEED_CHECKLIST: ShootingChecklistItem[] = [
  { id: 'chk_01', contentId: 'cnt_autumn_workspace', label: 'Primary camera angle calibrated & white balanced', completed: true, order: 1 },
  { id: 'chk_02', contentId: 'cnt_autumn_workspace', label: 'Warm desk accent lighting powered & tested (3200K)', completed: true, order: 2 },
  { id: 'chk_03', contentId: 'cnt_autumn_workspace', label: 'Cable lines concealed under walnut riser', completed: true, order: 3 },
  { id: 'chk_04', contentId: 'cnt_autumn_workspace', label: 'Record typing ASMR sound check (30s vertical)', completed: true, order: 4 },
  { id: 'chk_05', contentId: 'cnt_autumn_workspace', label: 'Record main intro hook & seasonal thesis', completed: false, order: 5 },
  { id: 'chk_06', contentId: 'cnt_autumn_workspace', label: 'Capture 5 b-roll detail cutaways for Instagram Reels', completed: false, order: 6 },
  { id: 'chk_07', contentId: 'cnt_autumn_workspace', label: 'Export master ProRes render to master-video.mp4', completed: false, order: 7 },
];

export const SEED_ANALYTICS: BasicAnalyticsMetric[] = [
  { platform: 'youtube', views: 84200, likes: 5420, comments: 780, shares: 1420, subscribersOrFollowersDelta: 540, updatedAt: '2026-09-24T04:00:00Z' },
  { platform: 'instagram', views: 24500, likes: 1980, comments: 240, shares: 890, subscribersOrFollowersDelta: 210, updatedAt: '2026-09-24T04:00:00Z' },
  { platform: 'tiktok', views: 12800, likes: 720, comments: 90, shares: 310, subscribersOrFollowersDelta: 85, updatedAt: '2026-09-24T04:00:00Z' },
  { platform: 'linkedin', views: 3000, likes: 110, comments: 10, shares: 45, subscribersOrFollowersDelta: 7, updatedAt: '2026-09-24T04:00:00Z' },
];
